---
name: Build CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_ACCOUNT: rockylinux

jobs:
  run_toolbox_builds:
    strategy:
      matrix:
        version:
          - major: 8
            arch: 'amd64, arm64'
          - major: 9
            arch: 'amd64, arm64, ppc64le, s390x'
    runs-on: ubuntu-latest
    name: Build and push toolbox images
    steps:
      - uses: actions/checkout@v3

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      
      - name: Build image
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          archs: ${{ matrix.version.arch }}
          build-args: |
            ImageVersion=${{ matrix.version.major }}
          containerfiles: |
            ./Dockerfile
          extra-args: |
            --squash
          labels: |
            name=rocky-toolbox
            version=${{ matrix.version.major }}
          oci: true
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ACCOUNT }}/rocky-toolbox:${{ matrix.version.major }}
